# config.yaml
bag_processing:
  bag_path: "../sceneflow_bags/day4/drone_data_2025-05-22_11-28-10_2025-05-22-11-28-11.bag"
  output_dir: "./results2/dynamic1"
  ros_version: "ROS1"
  max_time_diff: 0.1  # Max allowed time difference in seconds

  interval:
    start: 72
    end: 74.5
    highlights: [72.8, 72.9, 73.4]

processors:

  color_image:
    enabled: true
    type: "image"
    input_mappings:
      color_image: "/color_image"
    params:
      filename_prefix: "color_image_"
      generate_video: true            # Enable video
      video_filename: "color_output_video.mp4"
      video_fps: 30


  min_cbf_plot:
    enabled: true
    type: "min_cbf_plot"
    input_mappings:
      v_0: "/raw_psi_image"
      v_1: "/raw_h_image"
    params:
      k: 30.0
      y_limits: [null, 4.0]
      generate_video: true            # Enable video
      video_filename: "min_cbf_plot_video.mp4"
      video_fps: 30


  u_safety_error_plot:
    enabled: false
    type: "u_safety_error_plot"
    input_mappings:
      #u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"


  u_ref_error_plot:
    enabled: true
    type: "u_ref_error_plot"
    input_mappings:
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"


  u_sizes_plot:
    enabled: false
    type: "u_sizes_plot"
    input_mappings:
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"

  velocity_size_plot:
    enabled: false
    type: "velocity_size_plot"
    input_mappings:
      odometry: "/rig_node/odometry"

  snapshot_visualization:
    enabled: true
    type: "snapshot_visualization"
    input_mappings:
      sceneflow: "/scene_flow_processed"
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"
    params:
      axis_limits:
        x: [-1.5, 2.5]
        y: [-1, 1]
        z: [-0.75, 1.25]
      view_angle:
        elev: 20
        azim: 120
        roll: 0
      filename_prefix: "processed_"
      max_distance: 3.5
      u_scaling_factor: 0.5
      generate_video: true            # Enable video
      video_filename: "snapshot_viz_video.mp4"
      video_fps: 30

  snapshot_visualization_raw:
    enabled: false
    type: "snapshot_visualization"
    input_mappings:
      sceneflow: "/scene_flow_raw"
    params:
      axis_limits:
        x: [-1, 1]
        y: [-1, 1]
        z: [-1, 2.5]
      view_angle:
        elev: 20
        azim: 200
        roll: 90
      filename_prefix: "raw_"
      max_distance: 3.5

  cbf_value_image:
    enabled: true
    type: "cbf_value_image"
    input_mappings:
      v_0: '/psi_image'
      v_1: '/h_image'
    params:
      filename_prefix: "cbf_value_"
      generate_video: true            # Enable video
      video_filename: "cbf_value_video.mp4"
      video_fps: 30


  pc_path:
    enabled: true
    type: pointcloud_path_visualization
    params:
      sample_every_n:       5          # use every 5-th cloud
      max_time_diff:        0.05       # s, cloud ↔ odom sync tolerance
      max_points_per_cloud: 8000
      cmap: viridis
      axis_limits:
        x: [0.5, 3.5]  # X-axis limits in meters
        y: [1.5, 2.5]    # Y-axis limits in meters  
        z: [-1.2, 0.8]    # Z-axis limits in meters
      sample_every_n     : 5
      distance_threshold : 4
      point_size         : 15
      point_color_by     : time        # or 'distance', 'constant'
      point_cmap         : winter
      path_linewidth     : 5.0         # thicker line
      cmap               : inferno     # for CBF correction
      view_angle         : {elev: 15, azim: 105}
      u_scaling_factor: 0.25
    input_mappings:
      point_cloud: /depth_point_cloud
      odometry:    /rig_node/odometry
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"

  time_series_vectors:
    enabled: false
    type: "time_series_vector_visualization"
    input_mappings:
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"
    params:
      sample_interval: 0.1  # Sample every 0.2 seconds
      vector_scale: 0.2     # Scale vectors for visibility
      y_axis_limit: 1.0     # Y-axis range [-1, 1]
      z_axis_limit: 1.0     # Z-axis range [-1, 1]
      num_time_ticks: 6     # Number of time ticks on axis
      axis_indicator_length: 1  # Length of axis direction indicators
      view_angle:
        elev: 20    # Elevation angle
        azim: -60   # Azimuth angle
      filename_prefix: "control_vectors"

  angular_velocity_plot:
    enabled: true
    type: "angular_velocity_size_plot"
    input_mappings:
      odometry: "/rig_node/odometry"
    params: