# config.yaml
bag_processing:
  bag_path: "../sceneflow_bags/day4/drone_data_2025-05-22_11-28-10_2025-05-22-11-28-11.bag"
  output_dir: "./results/dynamic1"
  ros_version: "ROS1"
  max_time_diff: 0.1  # Max allowed time difference in seconds

  interval:
    start: 72
    end: 74
    highlights: [72, 72.5, 73, 73.5, 74]

processors:

  color_image:
    enabled: false
    type: "image"
    input_mappings:
      color_image: "/color_image"
    params:
      filename_prefix: "color_image_"


  min_cbf_plot:
    enabled: false
    type: "min_cbf_plot"
    input_mappings:
      v_0: "/raw_psi_image"
      v_1: "/raw_h_image"


  u_safety_error_plot:
    enabled: false
    type: "u_safety_error_plot"
    input_mappings:
      #u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"


  u_ref_error_plot:
    enabled: false
    type: "u_ref_error_plot"
    input_mappings:
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"


  u_sizes_plot:
    enabled: false
    type: "u_sizes_plot"
    input_mappings:
      u_ref: "/input_viz"
      u_safe: "/control_vector_viz_unfiltered"
      u_filtered: "/control_vector_viz_raw"
      u_actual: "/mavros/setpoint_raw/local_viz"

  velocity_size_plot:
    enabled: false
    type: "velocity_size_plot"
    input_mappings:
      odometry: "/rig_node/odometry"

  snapshot_visualization:
    enabled: true
    type: "snapshot_visualization"
    input_mappings:
      point_cloud: "/depth_point_cloud"
      reference: "/input_viz"
      control: "/control_vector_viz_raw"
    params:
      axis_limits:
        x: [-1, 2.5]
        y: [-1, 1]
        z: [-1, 1]
      view_angle:
        elev: 10
        azim: 90
